services:
  - type: web
    name: museo-reservas-api
    runtime: docker
    plan: free
    dockerfile: ./Dockerfile
    region: oregon
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: runtime
