services:
  - type: web
    name: museo-reservas-api
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: runtime
    region: oregon
    autoDeploy: true
